### ISSUE TITLE
Adaptation of `score()` to run on my custom bert version.

### ISSUE THREAD

**Issue by romualdoalan** [Tiiiger/bert_score#103]
Hello!

How i can use the function  `score(cands, refs, lang='others', verbose=True)` to my custom bert version? I want use [BERTimbau](https://github.com/neuralmind-ai/portuguese-bert) and not Multilingual for my avaliations. Can you help?

**Comment by felixgwu** [comment]
Hi @romualdoalan,

You may use `score(cands, refs, model_type='neuralmind/bert-base-portuguese-cased', num_layers=8, verbose=True)`.
Since the number of layers is not tuned, you have to specify the output of which layer you want to use explicitly.
[Here](https://github.com/Tiiiger/bert_score/tree/master/tune_layers) is an example of how we tune the number of layers on English data. 
Unfortunately, I couldn't find Portuguese in WMT16 & WMT17 where we tuned the model. You may need some other datasets to calculate the correlation with human scores.

Best,
Felix

**Comment by romualdoalan** [comment]
This solved!! :D

Thank you @felixgwu  for your quick answer!
