### ISSUE TITLE
Support for ByT5

### ISSUE THREAD

**Issue by long21wt** [Tiiiger/bert_score#113]
Hi,

Could you add ByT5 model to `model2layers`?
I tried BERTScore with ByT5, and it works, but haven't been able to tune the layer according to the WMT16 dataset. My process is always killed, even though I set the batch size to 4.

Thanks

**Comment by felixgwu** [comment]
Hi @long21wt,

I've added `google/byt5-small`, `google/byt5-base`, and `google/byt5-large` in a new commit.
I believe your process got killed because it ran out of main memory (not GPU memory). I faced a similar problem when I tried ByT5 on a machine with little memory.
I'm closing the issue for now, but please feel free to reopen if you have any other questions.

Best,
Felix
