### ISSUE TITLE
Running bert score examples

### ISSUE THREAD

**Issue by kaliaanup** [Tiiiger/bert_score#124]
Based on the instructions I can run the bert score as a command line and generate the P, R, and F values. However executing as a python code 

```python
import bert_score

cands = [
    "28-year-old chef found dead in San Francisco mall",
    "A 28-year-old chef who recently moved to San Francisco was found dead in the staircase of a local shopping center.",
    'The victim\'s brother said he cannot imagine anyone who would want to harm him,"Finally, it went uphill again at him."',
]
refs = [
    "28-Year-Old Chef Found Dead at San Francisco Mall",
    "A 28-year-old chef who had recently moved to San Francisco was found dead in the stairwell of a local mall this week.",
    "But the victim's brother says he can't think of anyone who would want to hurt him, saying, \"Things were finally going well for him.\"",
]

(P, R, F), hash_code = bert_score.score(
            cands, refs, model_type="roberta-large", num_layers=17, idf=True, batch_size=3, return_hash=True,
        )

print(P,R,F)
```

gives me the following error
```
AttributeError: partially initialized module 'bert_score' has no attribute 'score' (most likely due to a circular import)
```

**Comment by Tiiiger** [comment]
hi @kaliaanup 

are you using the newest version? did you install through pip or from source?

**Comment by Peterwwwww** [comment]
Hi @Tiiiger , 

I'm having the same issue, with similar example as above. And I did pip install bert-score at the begining.


ImportError: cannot import name 'BERTScorer' from partially initialized module 'bert_score' (most likely due to a circular import)


Could you provide a running bert score example of file to file comparison if it's possible? Thank you very much.



Here's what i did:

from bert_score import BERTScorer

refs = [['The dog bit the guy.', 'The dog had bit the man.'],
        ['It was not unexpected.', 'No one was surprised.'],
        ['The man bit him first.', 'The man had bitten the dog.']]

hyps = ['The dog bit the man.', "It wasn't surprising.", 'The man had just bitten him.']

scorer = BERTScorer(lang="en", rescale_with_baseline=True)
P, R, F1 = scorer.score(hyps, refs)

print(F1.mean())

**Comment by felixgwu** [comment]
Hi @Peterwwwww,

It is likely that you have a local file called `bert_score.py` which has the same name as our library and causes the import problem. Can you check that none of your files called `bert_score.py` and none of your folders called `bert_score`.

Best,
Felix

**Comment by Peterwwwww** [comment]
Hi @felixgwu,

Yes, you are right! It worked after I renamed the file.

Thank you 
Peter
