### ISSUE TITLE
Wrong default bert score.

### ISSUE THREAD

**Issue by zhaowei-wang98** [Tiiiger/bert_score#132]
Hi All,
I am using this repo through huggingface.datasets. If I input an empty reference or empty candidate, the default value is 0, while I didn't set `rescale_with_baseline` to be `True.` In this case, the default value should be -1 instead of 0, I think. So, the default value should be 0 if `rescale_with_baseline=True` and be -1 otherwise.
The related code:
https://github.com/Tiiiger/bert_score/blob/2a40716c7040a443e98edc15608fcbb163f268e4/bert_score/utils.py#L466

**Comment by Tiiiger** [comment]
hi @zhaowei-wang98 ,

I raised a very good question. In short, I think there is no good default value for an empty candidate sentence because mathematically it's undefined. That's why we print out these warnings to give people a heads-up.

Therefore, I don't think we will make any official changes in the package. If you feel that in your application, it makes sense to set the default value to a specific number, I suggest you postprocess the scores we return. 

Thank you and sorry for a late reply!
