### ISSUE TITLE
The best way using bert_score to evaluate text generation like VAE,GAN 

### ISSUE THREAD

**Issue by HOLMEScdk** [Tiiiger/bert_score#38]
Thanks for your implementation.
I am now using your method to evaluate the performance of generated text by VAEs, GANs models which samples a distribution from a space without references.  What's your suggestion to evaluate this kind of task? I didn't a detail description in your paper.  
Thanks!

**Comment by gmftbyGMFTBY** [comment]
In my view, I think this is the fatal weakness of the traditional word-overlap-based metrics (BLEU, ROUGE, METEOR and so on) and embedding-based metrics (Embedding Average, Vector Extrema, Greedy Matching, BERTScore and so on).

In my view, the best way to measure the performance of the VAE or GANs model (responses maybe very different with the references) is to use the learning-based metrics. The learning-based metric is first proposed by [ADEM](https://arxiv.org/abs/1708.07149), and [RUBER](https://arxiv.org/pdf/1701.03079.pdf) improves it. Recently, [BERT-RUBER](https://arxiv.org/pdf/1904.10635.pdf) leverages the BERT contextual embeddings for RUBER framework and achieves a very high correlation with human judgments e.g. state-of-ther-art.

I already implement the BERT-RUBER and RUBER in my repo [RUBER-and-BERT-RUBER](https://github.com/gmftbyGMFTBY/RUBER-and-Bert-RUBER). I already use the BERT-RUBER to evaluate my dialogue models and it works fine. If you have any questions, feel free to contact with me.

**Comment by felixgwu** [comment]
Hi @HOLMEScdk,

Thanks for your interest. BERTScore is designed for pairwise comparison between two sentences.
To evaluate generated text without references, people usually measure both their quality and diversity.  You may consider using HUSE ([Hashimoto et al.](https://arxiv.org/pdf/1904.02792.pdf)) or GLTR ([Gehrmann et al.](https://www.aclweb.org/anthology/P19-3019.pdf)).
OpenAI GPT2 detector ([Solaiman et al.](https://github.com/openai/gpt-2-output-dataset/tree/master/detector)) may also be a possible alternative. 

Admittedly, there can be some possible ways to extend BERTScore or BERT embeddings for this task. For instance, treating BERTScore as the distance measure between any two sentences, and estimating the earth mover's distance between your generated text and real text, i.e., moving each generated sentence to its nearest real sentence. However, since we haven't done any experiments on this, it's better to use the published methods mentioned above.

Please feel free to let us know if you have further questions.

Best,
Felix

**Comment by Tiiiger** [comment]
closing this for now but feel free to continue the thread.
