### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by wlvh** [Tiiiger/bert_score#40]
When I input the command in My linux
"bert-score -r example/refs.txt -c example/hyps.txt --lang en"
There is not any response and I have to force exit.
Can you help me solve it out?

**Comment by Tiiiger** [comment]
hi @wlvh are you running this code from China? 

I know in the past that it can take a while to download the pre-trained model in China. I suggest you to look into your network config (potentially putting on a vpn ... ). 

I believe this is not an expected behavior of this repo so I am closing for now. But feel free to continue this thread.
