### ISSUE TITLE
[QUESTION] Comparison to Sentence-BERT

### ISSUE THREAD

**Issue by loretoparisi** [Tiiiger/bert_score#45]
I was using BERT-Score since a while for STS task and so far it’s the best choice for sentence comparison in my opinion and tests on real world text, hence not necessarily on synthetic text.
I was wondering if there is any comparison to [Sentence-BERT](https://arxiv.org/abs/1908.10084) that has SOTA results in STS with a Siamese Net architecture. Code is [here](https://github.com/UKPLab/sentence-transformers).

Thank you!

**Comment by Tiiiger** [comment]
hi @loretoparisi, Thank you for your interest!

In BERTScore, we put a lot of thoughts into making a general, task-agnostic metric. Our intention is to reduce the bias in our evaluation metric so that people can apply it on many different tasks and have fair, consistent comparisons. 

That being said, when you do have a specific dataset you are working with, supervision from this specific domain can definitely help. On this note, you can compare BERTScore's performance on the QQP dataset, which around 78%, to that of SOTA supervised models, which is > 90%.

I hope my answer help. Closing for now but feel free to follow up.

**Comment by Neuronys** [comment]
Hi @loretoparisi 
Nils Reimers, the author of Sentence-BERT points me to this paper that may be interesting for you: https://arxiv.org/pdf/2004.13937.pdf
Cheers
Philippe

**Comment by loretoparisi** [comment]
@Neuronys thank so much, that's pretty interesting. Also just last night I was looking to new  BLEURT score, that we can add to this list! https://github.com/google-research/bleurt

**Comment by Neuronys** [comment]
Thanks @loretoparisi
