### ISSUE TITLE
Bert as an OCR metric

### ISSUE THREAD

**Issue by gaceladri** [Tiiiger/bert_score#52]
Hi, it would be useful is it can be used without reference. Just an ocr output and a similarity score between the output and the words in the embedding? Just thinking

**Comment by Tiiiger** [comment]
hi @gaceladri , I am not very familiar with OCR and how you evaluate it. 

I am happy to chat more if you can help provide more context/background.

**Comment by gaceladri** [comment]
@Tiiiger Well, it's a bit tricky, since, depending on the quality of your OCR model, the outputs can be more or less clear. 

For example if you don't have a supervised corpus that it use to be the case, you can not measure the performance of the model, normally already pre-trained and you don't use to have the supervised corpus. 

So my thinking is, can we measure the similarity of the outputs from the OCR and do... a cosine similarity? for example to some dictionary (the embedding of a BERT) and measure the performance of the OCR or directly replace those noisy outputs from the OCR model to the nearest words in the embedding. 

Do you know what I mean?

**Comment by Tiiiger** [comment]
I am not sure I follow but hey, feel free to give it a try. 

Most of the backend of BERTScore is in https://github.com/Tiiiger/bert_score/blob/master/bert_score/utils.py
You can reuse the code here to get the embeddings and pairwise cosine similarity. 

I am closing this issue for now because it is less relevant to the most common usage of this repo. However, feel free to reach out if you have any question about the code.
