### ISSUE TITLE
fine-tuning model according to my corpus

### ISSUE THREAD

**Issue by shikharsingla** [Tiiiger/bert_score#61]
Hi, 

I might be wrong but this module helps calculate similarity based on pre-trained models. 

I was wondering if there is a way to use your library and fine tune/incorporate according to my corpus. I have huge text corpus for my relevant case, I was wondering if model can be fine tuned then I would like to get similarity between words according to that model.

I can train a word2vec on my corpus for this and then get the similarity between the words but I believe BERT is better for such tasks.

Thanks a lot for your help
Shikhar

**Comment by felixgwu** [comment]
Hi @shikharsingla,

Yes, you can fine-tune a pre-trained BERT or RoBERTa on your own corpus using Huggingface's transformers (see [link](
https://github.com/huggingface/transformers/tree/master/examples/language-modeling) for an example).
After the model is fine-tuned, you can just use `--model` argument of bert-score to loaded your pretrained model.

Best,
Felix

**Comment by seyyedjavadrazavi** [comment]
> Hi @shikharsingla,
> 
> Yes, you can fine-tune a pre-trained BERT or RoBERTa on your own corpus using Huggingface's transformers (see [link](https://github.com/huggingface/transformers/tree/master/examples/language-modeling) for an example). After the model is fine-tuned, you can just use `--model` argument of bert-score to loaded your pretrained model.
> 
> Best, Felix

Hi [felixgwu](https://github.com/felixgwu)
Unfortunately, the link for example is expired. I have the Stack Overflow questions and need to fine-tune the bert-score with those questions to have a better prediction in similarity. As I saw in this issue, the better way is to fine-tune the Bert and then import fine-tuned Bert into the bert-score. 
Because I just have the questions without any tags, is there any other links for an explanation of how I can fine-tune Bert in an unsupervised way? 
Thanks in advance.
