### ISSUE TITLE
--model and --rescale-with-baseline can not be used together

### ISSUE THREAD

**Issue by L-Zhe** [Tiiiger/bert_score#71]
I use --model to load local model and I use --lang en --rescale-with-baseline to use rescale-with-baseline. The output shows :(hug_trans=3.0.2)-rescaled P: R: F: , but I found the numerical is same with the model without rescale-with-baseline. The command I used is as follow:
bert-score -r XXX -c XXX --model XXX --num_layers 17 --lang en --rescale-with-baseline

**Comment by Tiiiger** [comment]
hi @L-Zhe because we couldn't precompute the baselines for your local model, you cannot do `rescale-with-baseline`. This is an intended feature.

**Comment by L-Zhe** [comment]
> hi @L-Zhe because we couldn't precompute the baselines for your local model, you cannot do `rescale-with-baseline`. This is an intended feature.

Because of network limination, downloading the model directly is very slow, so I have to use the local model downloaded from BaiduPan. How could I do to use rescale with baseline?

**Comment by Tiiiger** [comment]
hi @L-Zhe, I see the issue here. One workaround would be to put your downloaded model into the huggingface cache folder. You might open an issue to the transformers repo to see how to do this. Here's a. relevant repo https://github.com/huggingface/transformers/issues/2323 .

A quick but less principled hack is to change the model type within this [code branch](https://github.com/Tiiiger/bert_score/blob/master/bert_score/score.py#L149). You would need to clone this repo, modify the code, and install locally from source.

**Comment by felixgwu** [comment]
Hi @L-Zhe, we just added a `--baseline_path` argument to specify a custom path of the baseline file in our master branch. 
For example, you can just set it to this [file](https://github.com/Tiiiger/bert_score/blob/master/bert_score/rescale_baseline/en/roberta-large.tsv) if you use roberta-large for English sentences.
We hope this helps.
