### ISSUE TITLE
the idf logic mades me confused

### ISSUE THREAD

**Issue by duongkstn** [Tiiiger/bert_score#75]
Hi, 
In your code (scorer.py), you wrote:
```
 - :param: `idf` (dict): use idf weighting, can also be a precomputed idf_dict
 - :param: `idf_sents` (List of str): use idf weighting, can also be a precomputed idf_dict
```

I want to use precomputed `my_dict` but I do not know which param should I use (`idf` or `idf_sents`). 
If I choose `idf`, then in `class BERTScorer:`, `self._idf` equals  `my_dict`, and `def idf(self):` returns `my_dict`. But in `__init__` function, you assigned `self._idf_dict = None` :( .
How could I assign `self._idf_dict = my_dict` ?

**Comment by Tiiiger** [comment]
hi @duongkstn sorry for the late reply, I am looking into this now.

**Comment by felixgwu** [comment]
Hi @duongkstn, sorry for confusing you. These comments are wrong.

`idf` is a boolean parameter to specify whether to use idf or not.
`idf_sents` is a list of sentences used to compute the idf.
You can set `idf=True` and provide a list to `idf_sents` so that it creates `self._idf_dict` automatically.
Alternatively, you can just set `idf=True` and assign `self._idf_dict = my_dict` if you have created the dictionary yourself.
