### ISSUE TITLE
BertScore not using GPU

### ISSUE THREAD

**Issue by MichaelJanz** [Tiiiger/bert_score#77]
Hi, I use bert_score out of python with the following code:

`P, R, F1 = score([summary], [src_text], lang='en', verbose=False, batch_size=1, device=0)`

However, my GPU is not used, but the CPU which makes it run pretty slow (checked top & nvidia-smi). I have got an rtx 2070 with 8GB, which is normally enough for other models. Also, I use the code above in a loop. Could that be a cause too?

**Comment by felixgwu** [comment]
Hi @MichaelJanz , we are using PyTorch as the backend, so the device should be set to a string `'cuda'` or `'cuda:0'` (if you when to specify the first GPU) to enable GPU usage.

**Comment by felixgwu** [comment]
Also, thank you for pointing this out. As you can see, our arguments are sometimes confusing. We are planning to add type checking in a newer version.

**Comment by MichaelJanz** [comment]
Hi @felixgwu and thank you for your answer. I updated my code to :
`P, R, F1 = score([summary], [src_text], lang='en', verbose=False, batch_size=1, device="cuda:0")`
But I still dont see any improvement. It rather looks like that cpu only is a very little bit faster, as it reached 9.79s/it with my data while with setting `device=cuda:0` it/s do not go below 10.

Could the reason be, that I use` batch_size=1` so the gpu advantages cannot be used?

**Comment by Tiiiger** [comment]
hi @MichaelJanz ,

Yes I think you would need a larger batch size to get the benefit. As a rule of thumb, choose a batch size that would basically fill all of your GPU memory.

Also, just for the sake of debugging, can you check your GPU utilization by `nvidia-smi`?

**Comment by MichaelJanz** [comment]
Yes, with a larger batch size, I haev a huge speed improvement. Thanks for that!
Although it is fast enough for my purposes now, I still see that my CPU usage goes to 100% while gpu is between 4% and 0%, this is what Nvidia-Smi says.

**Comment by Tiiiger** [comment]
@MichaelJanz 

I would suggest that instead of handling the batching manually as you do right now, you should input all of `summaries` and `src_texts` to the `score` function at once. The `score` function will handle the batching automatically.

Concretely, this means that you want to put everything in `results["source_texts"]` into `src_texts` and everything in `results["generated summaries"]` into `summaries`. 

There are two benefits:
1. the `score` function will create a new model during the call. so you want to avoid calling the `score` function multiple times, which will lead to a major overhead of creating the model. 
2. the `score` function does smart batching. it will put sequences of similar lengths together into one batch to avoid excessive padding. 

As a minor note, technically your batch size here is `4` because every time you are only evaluating 4 pairs of src and generated summaries. That's probably why you are seeing a very low GPU usage.

Closing this now, I expect it to work smoothly once you change the batching as suggested above.
