### ISSUE TITLE
Question: tf_idf feature?

### ISSUE THREAD

**Issue by amberhuang01** [Tiiiger/bert_score#99]
Hi guys,

Thanks for the brilliant work!

I'm trying to use bert_score with multireferences. I know there is a weighted feature using IDF, wondering if there is one using tf_idf?

Thank you :)

**Comment by Tiiiger** [comment]
hi @amberhuang01 

I didn't try TFIDF because typically the MT translations are very short and a term does not appear more than once. 

if you are interested, you can fork and modify our code base to do that. 

I would start modifying this line for TFIDF
https://github.com/Tiiiger/bert_score/blob/ded6c162cebf6b157f753a4506ec7f23ac26d217/bert_score/utils.py#L353
